analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_final_fields: true
    always_declare_return_types: true
    prefer_const_declarations: true
    avoid_positional_boolean_parameters: true
    prefer_typing_uninitialized_variables: true
    unnecessary_this: true
    sort_pub_dependencies: true
    prefer_single_quotes: true
    lines_longer_than_80_chars: false
